//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneTraineeManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CapstoneTraineeManagement.Resources.EmailTemplates", typeof(EmailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0},&lt;br&gt;&lt;br&gt;Congratulations! Your enrollment in the course has been successfully confirmed. Please find the program details below:&lt;ul&gt;&lt;li&gt;&lt;strong&gt;Program Name:&lt;/strong&gt; {1}&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Program Category:&lt;/strong&gt; {2}&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Duration:&lt;/strong&gt; {3}&lt;/li&gt;&lt;li&gt;&lt;strong&gt;Mode:&lt;/strong&gt; {4}&lt;/li&gt;&lt;/ul&gt;We’re excited to have you join us and look forward to supporting you on your learning journey.&lt;br&gt;&lt;br&gt;Additional details and access instructions will be shared with you shortly.&lt;br&gt;&lt;br&gt;If you have any qu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EnrollmentBody {
            get {
                return ResourceManager.GetString("EnrollmentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re Enrolled: Welcome to {0}.
        /// </summary>
        public static string EnrollmentSubject {
            get {
                return ResourceManager.GetString("EnrollmentSubject", resourceCulture);
            }
        }
    }
}
